# Generated by Django 3.2 on 2021-04-27 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myblog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'comments',
                'verbose_name_plural': 'comments',
                'ordering': ['-created_time'],
            },
        ),
    ]
