# Generated by Django 3.1.7 on 2021-03-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20210314_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='introductions',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(max_length=255),
        ),
    ]
