# Generated by Django 3.1.7 on 2021-04-05 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_auto_20210405_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_tag',
            new_name='snippet',
        ),
    ]
