# Generated by Django 3.1.7 on 2021-04-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0016_auto_20210405_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='comments',
        ),
    ]
