# Generated by Django 3.1.7 on 2021-04-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0018_auto_20210406_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views',
            new_name='total_views',
        ),
    ]
