# Generated by Django 3.1.7 on 2021-04-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0019_auto_20210406_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='total_views',
            new_name='views',
        ),
    ]
